vendas/core/urls.py
from django.urls import include, path
from vendas.core import views as c


app_name = 'core'


customer_patterns = [
    path('', view=c.CustomerList.as_view(), name='customer_list'),
    path('<int:pk>/', view=c.CustomerDetail.as_view(), name='customer_detail'),
    path('edit/<int:pk>/', view=c.CustomerUpdate.as_view(), name='customer_update'),
]

brand_patterns = [
    path('', view=c.BrandList.as_view(), name='brand_list'),
]

product_patterns = [
    path('', view=c.ProductList.as_view(), name='product_list'),
]

sale_patterns = [
    path('', view=c.SaleList.as_view(), name='sale_list'),
    path('add/', view=c.sale_create, name='sale_add'),
    path('<int:pk>/', view=c.SaleDetailView.as_view(), name='sale_detail'),
]

seller_patterns = [
    path('', view=c.SellerList.as_view(), name='seller_list'),
    path('<int:pk>/', view=c.SellerDetail.as_view(), name='seller_detail'),
]

urlpatterns = [
    path('', c.home, name='home'),
    path('about/', c.about, name='about'),
    path('customer/', include(customer_patterns)),
    path('brand/', include(brand_patterns)),
    path('product/', include(product_patterns)),
    path('sale/', include(sale_patterns)),
    path('seller/', include(seller_patterns)),
]

vendas/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path('', include('vendas.core.urls', namespace='core')),
    path('admin/', admin.site.urls),
]

vendas/core/models.py
from django.db import models
from django.urls import reverse_lazy
from django.utils.formats import number_format

gender_list = [('M', 'masculino'), ('F', 'feminino')]


class TimeStampedModel(models.Model):
    created = models.DateTimeField(
        'criado em', auto_now_add=True, auto_now=False)
    modified = models.DateTimeField(
        'modificado em', auto_now_add=False, auto_now=True)

    class Meta:
        abstract = True


class Person(TimeStampedModel):

    """ Person is abstract model """
    gender = models.CharField('gênero', max_length=1, choices=gender_list)
    cpf = models.CharField('CPF', max_length=11)
    firstname = models.CharField('Nome', max_length=20)
    lastname = models.CharField('Sobrenome', max_length=20)
    email = models.EmailField('e-mail', unique=True)
    phone = models.CharField('Fone', max_length=18)
    birthday = models.DateTimeField('Nascimento')

    class Meta:
        abstract = True
        ordering = ['firstname']

    def __str__(self):
        return self.firstname + " " + self.lastname
    full_name = property(__str__)


class Customer(Person):
    pass

    class Meta:
        verbose_name = 'cliente'
        verbose_name_plural = 'clientes'

    # clica na pessoa e retorna os detalhes dela
    def get_customer_url(self):
        return "/customer/%i" % self.id

    # clica em vendas e retorna as vendas da pessoa
    def get_sale_customer_url(self):
        return "/sale/?customer=%i" % self.id

    # vendas por pessoa
    def get_sales_count(self):
        return self.customer_sale.count()


class Seller(Person):
    active = models.BooleanField('ativo', default=True)
    internal = models.BooleanField('interno', default=True)
    commissioned = models.BooleanField('comissionado', default=True)
    commission = models.DecimalField(
        'comissão', max_digits=6, decimal_places=2, default=0.01, blank=True)

    class Meta:
        verbose_name = 'vendedor'
        verbose_name_plural = 'vendedores'

    # clica no vendedor e retorna os detalhes dele
    def get_seller_url(self):
        return "/seller/%i" % self.id

    # clica em vendas e retorna as vendas do vendedor
    def get_sale_seller_url(self):
        return "/sale/?seller=%i" % self.id

    # vendas por pessoa
    def get_sales_count(self):
        return self.seller_sale.count()

    def get_commission(self):
        return "%s" % number_format(self.commission * 100, 0)


class Brand(models.Model):
    brand = models.CharField('Marca', max_length=50, unique=True)

    class Meta:
        ordering = ['brand']
        verbose_name = 'marca'
        verbose_name_plural = 'marcas'

    def __str__(self):
        return self.brand


class Category(models.Model):
    id = models.CharField('Id', max_length=7, primary_key=True)
    category = models.CharField('Categoria', max_length=50, unique=True)

    class Meta:
        verbose_name = 'categoria'
        verbose_name_plural = 'categorias'

    def __str__(self):
        return self.category


class Product(models.Model):
    imported = models.BooleanField('Importado', default=False)
    outofline = models.BooleanField('Fora de linha', default=False)
    ncm = models.CharField('NCM', max_length=8)
    brand = models.ForeignKey(
        Brand,
        on_delete=models.CASCADE,
        verbose_name='marca'
    )
    product = models.CharField('Produto', max_length=100, unique=True)
    price = models.DecimalField('Preço', max_digits=7, decimal_places=2)
    ipi = models.DecimalField(
        'IPI',
        max_digits=3,
        decimal_places=2,
        blank=True
    )
    stock = models.IntegerField('Estoque atual')
    stock_min = models.PositiveIntegerField('Estoque mínimo', default=0)
    category = models.ForeignKey(
        Category,
        verbose_name='categoria',
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )

    class Meta:
        ordering = ['product']
        verbose_name = 'produto'
        verbose_name_plural = 'produtos'

    def __str__(self):
        return self.product

    def get_price(self):
        return "R$ %s" % number_format(self.price, 2)

    def get_ipi(self):
        return "%s" % number_format(self.ipi * 100, 0)


class Sale(TimeStampedModel):
    customer = models.ForeignKey(
        'Customer',
        related_name='customer_sale',
        verbose_name='cliente',
        on_delete=models.CASCADE,
    )
    seller = models.ForeignKey(
        'Seller',
        related_name='seller_sale',
        verbose_name='vendedor',
        on_delete=models.CASCADE,
    )

    class Meta:
        verbose_name = 'venda'
        verbose_name_plural = 'vendas'

    def __str__(self):
        return "%03d" % self.id + "/%s" % self.created.strftime('%y')
    codigo = property(__str__)

    def get_absolute_url(self):
        return reverse_lazy('core:sale_detail', pk=self.pk)

    def get_detalhe(self):
        return "/sale/%i" % self.id

    # conta os itens em cada venda
    def get_itens(self):
        return self.sales_det.count()

    def get_total(self):
        qs = self.sales_det.filter(sale=self.pk).values_list(
            'price_sale', 'quantity') or 0
        t = 0 if isinstance(qs, int) else sum(map(lambda q: q[0] * q[1], qs))
        return "R$ %s" % number_format(t, 2)


class SaleDetail(models.Model):
    sale = models.ForeignKey(
        Sale,
        related_name='sales_det',
        on_delete=models.CASCADE,
    )
    product = models.ForeignKey(
        Product,
        related_name='product_det',
        verbose_name='produto',
        on_delete=models.CASCADE,
    )
    quantity = models.PositiveSmallIntegerField('quantidade')
    price_sale = models.DecimalField(
        'Preço de venda', max_digits=6, decimal_places=2, default=0)
    ipi_sale = models.DecimalField(
        'IPI', max_digits=3, decimal_places=2, default=0.1)

    def __str__(self):
        return str(self.sale)

    def get_subtotal(self):
        return self.price_sale * (self.quantity or 0)

    subtotal = property(get_subtotal)

    def getID(self):
        return "%04d" % self.id

    def price_sale_formated(self):
        return "R$ %s" % number_format(self.price_sale, 2)

    def get_ipi(self):
        return "%s" % number_format(self.ipi_sale * 100, 0)

    def subtotal_formated(self):
        return "R$ %s" % number_format(self.subtotal, 2)

vendas/core/forms.py
from django import forms
from .models import Sale, SaleDetail


class SaleForm(forms.ModelForm):

    class Meta:
        model = Sale
        fields = '__all__'


class SaleDetailForm(forms.ModelForm):

    class Meta:
        model = SaleDetail
        fields = '__all__'

vendas/core/views.py
from django.shortcuts import render, resolve_url
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.db.models import F, Count
from django.views.generic import TemplateView, ListView, DetailView
from django.views.generic.edit import UpdateView
from django.forms.models import inlineformset_factory
from .models import Customer, Seller, Brand, Product, Sale, SaleDetail
from .forms import SaleForm, SaleDetailForm
from .mixins import CounterMixin, FirstnameSearchMixin


home = TemplateView.as_view(template_name='index.html')

about = TemplateView.as_view(template_name='about.html')


class CustomerList(CounterMixin, FirstnameSearchMixin, ListView):
    template_name = 'core/person/customer_list.html'
    model = Customer
    paginate_by = 8


class CustomerDetail(DetailView):
    template_name = 'core/person/customer_detail.html'
    model = Customer


class CustomerUpdate(UpdateView):
    template_name = 'core/person/customer_edit.html'
    model = Customer
    success_url = reverse_lazy('customer_detail')


class SellerList(CounterMixin, FirstnameSearchMixin, ListView):
    template_name = 'core/person/seller_list.html'
    model = Seller
    paginate_by = 8


class SellerDetail(DetailView):
    template_name = 'core/person/seller_detail.html'
    model = Seller


class BrandList(CounterMixin, ListView):
    template_name = 'core/product/brand_list.html'
    model = Brand


class ProductList(CounterMixin, ListView):
    template_name = 'core/product/product_list.html'
    model = Product
    paginate_by = 100

    def get_queryset(self):
        p = Product.objects.all()
        q = self.request.GET.get('search_box')
        # buscar por produto
        if q is not None:
            p = p.filter(product__icontains=q)
        # filtra produtos em baixo estoque
        if self.request.GET.get('filter_link', False):
            p = p.filter(stock__lt=F('stock_min'))
        # filtra produtos fora de linha
        if self.request.GET.get('outofline', False):
            p = p.filter(outofline=1)
        return p


def sale_create(request):
    order_forms = Sale()
    item_order_formset = inlineformset_factory(
        Sale, SaleDetail, form=SaleDetailForm, extra=0, can_delete=False,
        min_num=1, validate_min=True)

    if request.method == 'POST':
        forms = SaleForm(request.POST, request.FILES,
                         instance=order_forms, prefix='main')
        formset = item_order_formset(
            request.POST, request.FILES, instance=order_forms, prefix='product')

        if forms.is_valid() and formset.is_valid():
            forms = forms.save()
            formset.save()
            return HttpResponseRedirect(resolve_url('core:sale_detail', forms.pk))

    else:
        forms = SaleForm(instance=order_forms, prefix='main')
        formset = item_order_formset(instance=order_forms, prefix='product')

    context = {
        'forms': forms,
        'formset': formset,
    }

    return render(request, 'core/sale/sale_form.html', context)


class SaleList(CounterMixin, ListView):
    template_name = 'core/sale/sale_list.html'
    model = Sale
    paginate_by = 20

    def get_queryset(self):
        # filtra vendas com um item
        if 'filter_sale_one' in self.request.GET:
            return Sale.objects.annotate(
                itens=Count('sales_det')).filter(itens=1)
        # filtra vendas com zero item
        if 'filter_sale_zero' in self.request.GET:
            return Sale.objects.annotate(
                itens=Count('sales_det')).filter(itens=0)
        # filtros no queryset
        qs = super(SaleList, self).get_queryset()
        # clica no cliente e retorna as vendas dele
        if 'customer' in self.request.GET:
            qs = qs.filter(customer=self.request.GET['customer'])
        # clica no vendedor e retorna as vendas dele
        if 'seller' in self.request.GET:
            qs = qs.filter(seller=self.request.GET['seller'])
        return qs


class SaleDetailView(DetailView):
    template_name = 'core/sale/sale_detail.html'
    model = Sale
    context_object_name = 'Sale'

    def get_context_data(self, **kwargs):
        sd = SaleDetail.objects.filter(sale=self.object)
        context = super(SaleDetailView, self).get_context_data(**kwargs)
        context['count'] = sd.count()
        context['Itens'] = sd
        return context

vendas/core/templates/_pagination.html
<!-- pagination -->
        <div class="row text-center">
            <div class="col-lg-12">
                <ul class="pagination">
					{% if page_obj.has_previous %}
						<li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
					{% endif %}
					{% for pg in page_obj.paginator.page_range %}
						{% if page_obj.number == pg %}
							<li class="active"><a href="?page={{ pg }}">{{ pg }}</a></li>
						{% else %}
							<li><a href="?page={{ pg }}">{{ pg }}</a></li>
						{% endif %}
					{% endfor %}
					{% if page_obj.has_next %}
						<li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
					{% endif %}
				</ul>
			</div>
		</div>

vendas/core/templates/about.html
{% extends 'base.html' %}

{% block content %}

	<div class="container">
		<h1>Objetivo</h1>
		<p>Projeto escrito em Django para explorar todos os recursos do framework junto com todas as possibilidades de regras de negócio requisitadas num projeto real.</p>
		<p>Obs: Todos os nomes e valores são fictícios. Qualquer semelhança é mera coincidência.</p>

		<h1>Requisitos</h1>

		<ul>
			<li>o sistema vendas gerencia produtos por categoria.</li>
			<li>cada produto possui: categoria, preço e imagem, além de ser importado ou não, e estar fora de linha ou não.</li>
			<li>cada cliente possui: CPF, nome, sobrenome, email e telefone.</li>
			<li>cada cliente pode fazer uma venda e cada venda pode conter vários produtos, cada um com sua quantidade e o valor total da venda.</li>
			<li>o sistema deve pesquisar os produtos retornando o preço e a quantidade disponível.</li>
			<li>o sistema deve gerar um relatório com total geral e estatísticas dos produtos mais vendidos.</li>
		</ul>
		<p>Inicialmente eu quero explorar as bibliotecas do <a href="https://docs.djangoproject.com/en/dev/ref/class-based-views/">class based views</a> como <a href="https://docs.djangoproject.com/en/dev/ref/class-based-views/base/#templateview">TemplateView</a>, <a href="https://docs.djangoproject.com/en/dev/ref/class-based-views/generic-display/#listview">ListView</a> e <a href="https://docs.djangoproject.com/en/dev/ref/class-based-views/generic-editing/#formview">FormView</a>.</p>
	</div>

{% endblock %}

vendas/core/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>

  {% load static from staticfiles %}

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="{% static "img/cart.png" %}">

    {% block title %}
      <title>Vendas</title>
    {% endblock title %}

    <!-- Bootstrap Core CSS -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static "css/rgscale.css" %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static "font-awesome/css/font-awesome.min.css" %}" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">


    <!-- MENU -->
    {% include "menu_landpage.html" %}


    <!-- Intro Header -->
    <header class="intro">
        <div class="intro-body">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <a href="#about" class="btn btn-circle page-scroll">
                            <i class="fa fa-angle-double-down animated"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- About Section -->
    <section id="about" class="container content-section text-center">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <p>Vendas é um projeto escrito em Django para explorar todos os recursos do framework junto com todas as possibilidades de regras de negócio requisitadas num projeto real.</p>
                <p>Obs: Todos os nomes e valores são fictícios. Qualquer semelhança é mera coincidência.</p>
                <p>Veja o projeto no <a href="https://github.com/rg3915/vendas">GitHub</a>.</p>
            </div>
        </div>
    </section>

    <!-- Services Section -->
    <!-- <section id="service" class="container content-section text-center">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis deleniti a perspiciatis accusantium enim quas aliquam dolorem at obcaecati vitae quos tempore ad, sit iste illo et aliquid quo soluta?</p>
            </div>
        </div>
    </section> -->

    <!-- Services Section -->
    <section id="services" class="container content-section text-center">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading">Serviços</h2>
            </div>
        </div>
        <div class="row text-center">
            <div class="col-md-4"><a href="{% url 'core:product_list' %}">
                <span class="fa-stack fa-4x">
                    <i class="fa fa-circle fa-stack-2x text-orange"></i>
                    <i class="fa fa-tags fa-stack-1x fa-inverse"></i>
                </span></a>
                <h4 class="service-heading"><a href="{% url 'core:product_list' %}">Produtos</a></h4>
            </div>
            <div class="col-md-4">
                <span class="fa-stack fa-4x"><a href="{% url 'core:sale_list' %}">
                    <i class="fa fa-circle fa-stack-2x text-orange"></i>
                    <i class="fa fa-shopping-cart fa-stack-1x fa-inverse"></i>
                </span></a>
                <h4 class="service-heading"><a href="{% url 'core:sale_list' %}">Vendas</a></h4>
            </div>
            <div class="col-md-4">
                <span class="fa-stack fa-4x"><a href="{% url 'core:customer_list' %}">
                    <i class="fa fa-circle fa-stack-2x text-orange"></i>
                    <i class="fa fa-user fa-stack-1x fa-inverse"></i>
                </span></a>
                <h4 class="service-heading"><a href="{% url 'core:customer_list' %}">Clientes</a></h4>
            </div>
        </div>
    </section>

    <!-- Download Section -->
    <section id="download" class="content-section text-center">
        <div class="download-section">
            <div class="container">
                <div class="col-lg-8 col-lg-offset-2">
                    <h2>Download do projeto</h2>
                    <p>Você pode baixar o projeto no GitHub.</p>
                    <a href="https://github.com/rg3915/vendas" class="btn btn-default btn-lg">Download GitHub</a>
                </div>
            </div>
        </div>
    </section>

    <!-- Contact Section -->
    <section id="contact" class="container content-section text-center">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <ul class="list-inline social-buttons">
                    <li>
                        <a href="https://twitter.com/rg3915"><i class="fa fa-twitter"></i></a>
                    </li>
                    <li>
                        <a href="https://github.com/rg3915/vendas"><i class="fa fa-github fa-fw"></i></a>
                    </li>
                    <li>
                        <a href="https://plus.google.com/+R%C3%A9gisSilvaSantos/posts"><i class="fa fa-google-plus fa-fw"></i></a>
                    </li>
                </ul>
            </div>
        </div>
    </section>

    <!-- Map Section -->
    <!-- <div id="map"></div> -->


    <!-- Footer -->
    <footer>
        <div class="container text-left">
            <p>Régis Santos &copy; 2017 &middot; all rights reserved.</p>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="{% static "js/jquery.js" %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static "js/bootstrap.min.js" %}"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static "js/jquery.easing.min.js" %}"></script>

    <!-- Google Maps API Key - Use your own API key to enable the map feature. More information on the Google Maps API can be found at https://developers.google.com/maps/ -->
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCRngKslUGJTlibkQ3FkfTxj3Xss1UlZDA&sensor=false"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{% static "js/grayscale.js" %}"></script>

</body>

</html>

vendas/core/templates/menu.html
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'core:home' %}">Vendas</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'core:product_list' %}"><span class="glyphicon glyphicon-tags"></span> Produtos</a></li>
            <li><a href="{% url 'core:sale_list' %}"><span class="glyphicon glyphicon-shopping-cart"></span> Vendas</a></li>
            <li><a href="{% url 'core:customer_list' %}"><span class="glyphicon glyphicon-user"></span> Clientes</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span> Admin <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li class="dropdown-header">Cadastro de Produtos</li>
                <li><a href="{% url 'core:product_list' %}">Produto</a></li>
                <li><a href="{% url 'core:brand_list' %}">Marca</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Cadastro de Pessoas</li>
                <li><a href="{% url 'core:customer_list' %}">Cliente</a></li>
                <li><a href="{% url 'core:seller_list' %}">Vendedor</a></li>
                <!-- <li><a href="#">Contato</a></li>
                <li><a href="#">Fornecedor</a></li>
                <li><a href="#">Funcionário</a></li> -->
              </ul>
            </li>
            <!-- <li><a href="#"><span class="glyphicon glyphicon-flag"></span> Estoque</a></li> -->
          </ul>
          <!-- <form class="navbar-form navbar-right">
            <div class="form-group">
              <input type="text" placeholder="Email" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Password" class="form-control">
            </div>
            <button type="submit" class="btn btn-success">Sign in</button>
          </form> -->
          <ul class="nav navbar-nav navbar-right">
            <!-- <li><a href="#"><span class="glyphicon glyphicon-cog"></span> Config</a></li> -->
            <li><a href="{% url 'core:about' %}"><span class="glyphicon glyphicon-exclamation-sign"></span> Sobre</a></li>
            <!-- <li><a href="#"><span class="glyphicon glyphicon-question-sign"></span> Ajuda</a></li> -->
          </ul>
        </div><!--/.navbar-collapse -->
      </div>
    </div>

vendas/core/templates/menu_landpage.html
    <!-- Navigation -->
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">
                    <i class="fa fa-play-circle"></i>  <span class="light">Vendas</span>
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-main-collapse">
                <ul class="nav navbar-nav">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#services"><span class="glyphicon glyphicon-send"></span> Serviços</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="{% url 'core:product_list' %}"><span class="glyphicon glyphicon-tags"></span> Produtos</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="{% url 'core:sale_list' %}"><span class="glyphicon glyphicon-shopping-cart"></span> Vendas</a>
                    </li>
                    <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span> Admin <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li class="dropdown-header">Cadastro de Produtos</li>
                            <li><a class="page-scroll" href="{% url 'core:product_list' %}">Produto</a></li>
                            <li><a href="{% url 'core:brand_list' %}">Marca</a></li>
                            <li class="divider"></li>
                            <li class="dropdown-header">Cadastro de Pessoas</li>
                            <li><a href="{% url 'core:customer_list' %}">Cliente</a></li>
                            <li><a href="{% url 'core:seller_list' %}">Vendedor</a></li>
                            <!-- <li><a href="#">Contato</a></li>
                            <li><a href="#">Fornecedor</a></li>
                            <li><a href="#">Funcionário</a></li> -->
                        </ul>
                    </li>
                    <!-- <li>
                        <a class="page-scroll" href="#about">Estoque</a>
                    </li> -->
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <!-- <li>
                        <a class="page-scroll" href="#about">Config</a>
                    </li> -->
                    <li>
                        <a class="page-scroll" href="#about"><span class="glyphicon glyphicon-exclamation-sign"></span> Sobre</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#download"><span class="glyphicon glyphicon-download-alt"></span> Download</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#contact"><span class="glyphicon glyphicon-comment"></span> Contato</a>
                    </li>
                    <!-- <li>
                        <a class="page-scroll" href="#contact">Ajuda</a>
                    </li> -->
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>