vendas/core/urls.py
from django.urls import include, path
from vendas.core import views as c


app_name = 'core'


customer_patterns = [
    path('', view=c.CustomerList.as_view(), name='customer_list'),
    path('<int:pk>/', view=c.CustomerDetail.as_view(), name='customer_detail'),
    path('edit/<int:pk>/', view=c.CustomerUpdate.as_view(), name='customer_update'),
]

brand_patterns = [
    path('', view=c.BrandList.as_view(), name='brand_list'),
]

product_patterns = [
    path('', view=c.ProductList.as_view(), name='product_list'),
]

sale_patterns = [
    path('', view=c.SaleList.as_view(), name='sale_list'),
    path('add/', view=c.sale_create, name='sale_add'),
    path('<int:pk>/', view=c.SaleDetailView.as_view(), name='sale_detail'),
]

seller_patterns = [
    path('', view=c.SellerList.as_view(), name='seller_list'),
    path('<int:pk>/', view=c.SellerDetail.as_view(), name='seller_detail'),
]

urlpatterns = [
    path('', c.home, name='home'),
    path('about/', c.about, name='about'),
    path('customer/', include(customer_patterns)),
    path('brand/', include(brand_patterns)),
    path('product/', include(product_patterns)),
    path('sale/', include(sale_patterns)),
    path('seller/', include(seller_patterns)),
]

vendas/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path('', include('vendas.core.urls', namespace='core')),
    path('admin/', admin.site.urls),
]

vendas/core/models.py
from django.db import models
from django.urls import reverse_lazy
from django.utils.formats import number_format

gender_list = [('M', 'masculino'), ('F', 'feminino')]


class TimeStampedModel(models.Model):
    created = models.DateTimeField(
        'criado em', auto_now_add=True, auto_now=False)
    modified = models.DateTimeField(
        'modificado em', auto_now_add=False, auto_now=True)

    class Meta:
        abstract = True


class Person(TimeStampedModel):

    """ Person is abstract model """
    gender = models.CharField('gênero', max_length=1, choices=gender_list)
    cpf = models.CharField('CPF', max_length=11)
    firstname = models.CharField('Nome', max_length=20)
    lastname = models.CharField('Sobrenome', max_length=20)
    email = models.EmailField('e-mail', unique=True)
    phone = models.CharField('Fone', max_length=18)
    birthday = models.DateTimeField('Nascimento')

    class Meta:
        abstract = True
        ordering = ['firstname']

    def __str__(self):
        return self.firstname + " " + self.lastname
    full_name = property(__str__)


class Customer(Person):
    pass

    class Meta:
        verbose_name = 'cliente'
        verbose_name_plural = 'clientes'

    # clica na pessoa e retorna os detalhes dela
    def get_customer_url(self):
        return "/customer/%i" % self.id

    # clica em vendas e retorna as vendas da pessoa
    def get_sale_customer_url(self):
        return "/sale/?customer=%i" % self.id

    # vendas por pessoa
    def get_sales_count(self):
        return self.customer_sale.count()


class Seller(Person):
    active = models.BooleanField('ativo', default=True)
    internal = models.BooleanField('interno', default=True)
    commissioned = models.BooleanField('comissionado', default=True)
    commission = models.DecimalField(
        'comissão', max_digits=6, decimal_places=2, default=0.01, blank=True)

    class Meta:
        verbose_name = 'vendedor'
        verbose_name_plural = 'vendedores'

    # clica no vendedor e retorna os detalhes dele
    def get_seller_url(self):
        return "/seller/%i" % self.id

    # clica em vendas e retorna as vendas do vendedor
    def get_sale_seller_url(self):
        return "/sale/?seller=%i" % self.id

    # vendas por pessoa
    def get_sales_count(self):
        return self.seller_sale.count()

    def get_commission(self):
        return "%s" % number_format(self.commission * 100, 0)


class Brand(models.Model):
    brand = models.CharField('Marca', max_length=50, unique=True)

    class Meta:
        ordering = ['brand']
        verbose_name = 'marca'
        verbose_name_plural = 'marcas'

    def __str__(self):
        return self.brand


class Category(models.Model):
    id = models.CharField('Id', max_length=7, primary_key=True)
    category = models.CharField('Categoria', max_length=50, unique=True)

    class Meta:
        verbose_name = 'categoria'
        verbose_name_plural = 'categorias'

    def __str__(self):
        return self.category


class Product(models.Model):
    imported = models.BooleanField('Importado', default=False)
    outofline = models.BooleanField('Fora de linha', default=False)
    ncm = models.CharField('NCM', max_length=8)
    brand = models.ForeignKey(
        Brand,
        on_delete=models.CASCADE,
        verbose_name='marca'
    )
    product = models.CharField('Produto', max_length=100, unique=True)
    price = models.DecimalField('Preço', max_digits=7, decimal_places=2)
    ipi = models.DecimalField(
        'IPI',
        max_digits=3,
        decimal_places=2,
        blank=True
    )
    stock = models.IntegerField('Estoque atual')
    stock_min = models.PositiveIntegerField('Estoque mínimo', default=0)
    category = models.ForeignKey(
        Category,
        verbose_name='categoria',
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )

    class Meta:
        ordering = ['product']
        verbose_name = 'produto'
        verbose_name_plural = 'produtos'

    def __str__(self):
        return self.product

    def get_price(self):
        return "R$ %s" % number_format(self.price, 2)

    def get_ipi(self):
        return "%s" % number_format(self.ipi * 100, 0)


class Sale(TimeStampedModel):
    customer = models.ForeignKey(
        'Customer',
        related_name='customer_sale',
        verbose_name='cliente',
        on_delete=models.CASCADE,
    )
    seller = models.ForeignKey(
        'Seller',
        related_name='seller_sale',
        verbose_name='vendedor',
        on_delete=models.CASCADE,
    )

    class Meta:
        verbose_name = 'venda'
        verbose_name_plural = 'vendas'

    def __str__(self):
        return "%03d" % self.id + "/%s" % self.created.strftime('%y')
    codigo = property(__str__)

    def get_absolute_url(self):
        return reverse_lazy('core:sale_detail', pk=self.pk)

    def get_detalhe(self):
        return "/sale/%i" % self.id

    # conta os itens em cada venda
    def get_itens(self):
        return self.sales_det.count()

    def get_total(self):
        qs = self.sales_det.filter(sale=self.pk).values_list(
            'price_sale', 'quantity') or 0
        t = 0 if isinstance(qs, int) else sum(map(lambda q: q[0] * q[1], qs))
        return "R$ %s" % number_format(t, 2)


class SaleDetail(models.Model):
    sale = models.ForeignKey(
        Sale,
        related_name='sales_det',
        on_delete=models.CASCADE,
    )
    product = models.ForeignKey(
        Product,
        related_name='product_det',
        verbose_name='produto',
        on_delete=models.CASCADE,
    )
    quantity = models.PositiveSmallIntegerField('quantidade')
    price_sale = models.DecimalField(
        'Preço de venda', max_digits=6, decimal_places=2, default=0)
    ipi_sale = models.DecimalField(
        'IPI', max_digits=3, decimal_places=2, default=0.1)

    def __str__(self):
        return str(self.sale)

    def get_subtotal(self):
        return self.price_sale * (self.quantity or 0)

    subtotal = property(get_subtotal)

    def getID(self):
        return "%04d" % self.id

    def price_sale_formated(self):
        return "R$ %s" % number_format(self.price_sale, 2)

    def get_ipi(self):
        return "%s" % number_format(self.ipi_sale * 100, 0)

    def subtotal_formated(self):
        return "R$ %s" % number_format(self.subtotal, 2)

vendas/core/forms.py
from django import forms
from .models import Sale, SaleDetail


class SaleForm(forms.ModelForm):

    class Meta:
        model = Sale
        fields = '__all__'


class SaleDetailForm(forms.ModelForm):

    class Meta:
        model = SaleDetail
        fields = '__all__'

vendas/core/views.py
from django.shortcuts import render, resolve_url
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.db.models import F, Count
from django.views.generic import TemplateView, ListView, DetailView
from django.views.generic.edit import UpdateView
from django.forms.models import inlineformset_factory
from .models import Customer, Seller, Brand, Product, Sale, SaleDetail
from .forms import SaleForm, SaleDetailForm
from .mixins import CounterMixin, FirstnameSearchMixin


home = TemplateView.as_view(template_name='index.html')

about = TemplateView.as_view(template_name='about.html')


class CustomerList(CounterMixin, FirstnameSearchMixin, ListView):
    template_name = 'core/person/customer_list.html'
    model = Customer
    paginate_by = 8


class CustomerDetail(DetailView):
    template_name = 'core/person/customer_detail.html'
    model = Customer


class CustomerUpdate(UpdateView):
    template_name = 'core/person/customer_edit.html'
    model = Customer
    success_url = reverse_lazy('customer_detail')


class SellerList(CounterMixin, FirstnameSearchMixin, ListView):
    template_name = 'core/person/seller_list.html'
    model = Seller
    paginate_by = 8


class SellerDetail(DetailView):
    template_name = 'core/person/seller_detail.html'
    model = Seller


class BrandList(CounterMixin, ListView):
    template_name = 'core/product/brand_list.html'
    model = Brand


class ProductList(CounterMixin, ListView):
    template_name = 'core/product/product_list.html'
    model = Product
    paginate_by = 100

    def get_queryset(self):
        p = Product.objects.all()
        q = self.request.GET.get('search_box')
        # buscar por produto
        if q is not None:
            p = p.filter(product__icontains=q)
        # filtra produtos em baixo estoque
        if self.request.GET.get('filter_link', False):
            p = p.filter(stock__lt=F('stock_min'))
        # filtra produtos fora de linha
        if self.request.GET.get('outofline', False):
            p = p.filter(outofline=1)
        return p


def sale_create(request):
    order_forms = Sale()
    item_order_formset = inlineformset_factory(
        Sale, SaleDetail, form=SaleDetailForm, extra=0, can_delete=False,
        min_num=1, validate_min=True)

    if request.method == 'POST':
        forms = SaleForm(request.POST, request.FILES,
                         instance=order_forms, prefix='main')
        formset = item_order_formset(
            request.POST, request.FILES, instance=order_forms, prefix='product')

        if forms.is_valid() and formset.is_valid():
            forms = forms.save()
            formset.save()
            return HttpResponseRedirect(resolve_url('core:sale_detail', forms.pk))

    else:
        forms = SaleForm(instance=order_forms, prefix='main')
        formset = item_order_formset(instance=order_forms, prefix='product')

    context = {
        'forms': forms,
        'formset': formset,
    }

    return render(request, 'core/sale/sale_form.html', context)


class SaleList(CounterMixin, ListView):
    template_name = 'core/sale/sale_list.html'
    model = Sale
    paginate_by = 20

    def get_queryset(self):
        # filtra vendas com um item
        if 'filter_sale_one' in self.request.GET:
            return Sale.objects.annotate(
                itens=Count('sales_det')).filter(itens=1)
        # filtra vendas com zero item
        if 'filter_sale_zero' in self.request.GET:
            return Sale.objects.annotate(
                itens=Count('sales_det')).filter(itens=0)
        # filtros no queryset
        qs = super(SaleList, self).get_queryset()
        # clica no cliente e retorna as vendas dele
        if 'customer' in self.request.GET:
            qs = qs.filter(customer=self.request.GET['customer'])
        # clica no vendedor e retorna as vendas dele
        if 'seller' in self.request.GET:
            qs = qs.filter(seller=self.request.GET['seller'])
        return qs


class SaleDetailView(DetailView):
    template_name = 'core/sale/sale_detail.html'
    model = Sale
    context_object_name = 'Sale'

    def get_context_data(self, **kwargs):
        sd = SaleDetail.objects.filter(sale=self.object)
        context = super(SaleDetailView, self).get_context_data(**kwargs)
        context['count'] = sd.count()
        context['Itens'] = sd
        return context

vendas/core/templates/core/sale/sale_detail.html
{% extends 'base.html' %}

{% block content %}
	<h1><b>Venda:</b> {{ Sale.codigo }}</h1>
	
	<h2>
		<b>Cliente:</b> {{ Sale.customer.full_name }}
		<spam class="pull-right"><b>Vendedor:</b> {{ Sale.seller.full_name }}</spam>	
	</h2>

		<p><b>Data:</b> {{ Sale.created }}</p>
		<div>
			<table class="table">
				<thead>
					<tr>
						<th>NCM</th>
						<th>Produto</th>
						<th class="text-center">Quantidade</th>
						<th class="text-right">Preço de venda</th>
						<th class="text-right">Subtotal</th>
					</tr>
				</thead>
				<tbody>
				{% for item in Itens %}
					<tr>
						<td>{{ item.product.ncm }} </td>
						<td>{{ item.product.product }}</a></td>
						<td class="text-center">{{ item.quantity }}</td>
						<td class="text-right">{{ item.price_sale_formated }}</td>
						<td class="text-right">{{ item.subtotal_formated }}</td>
					</tr>
				{% empty %}
					<p>Sem itens na lista.</p>
				{% endfor %}
				</tbody>
			</table>
		</div>

		<hr>

		<h3 class="text-right"><b>Total:</b> <span class="label label-info">{{ Sale.get_total }}</span></h3>
		<!-- <p class="text-right">Obs: IPI não calculado.</p> -->
		<p>
			<a href="{% url 'core:sale_list' %}"><span class="glyphicon glyphicon-chevron-left">Voltar</span></a>
		</p>
	</div>

{% endblock content %}

vendas/core/templates/core/sale/sale_form.html
{% extends 'base.html' %}

{% load bootstrap %}

{% block title %}
  <title>Nova Venda</title>
{% endblock title %}

{# Adding select2 css #}
{% block css %}
  <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet"/>
{% endblock %}

{# Adding select2 js #}
{% block js %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
{% endblock %}

{% block content %}

  <!-- <div class="row">
      <div class="col-md-6 col-md-offset-3">
          <h1 class="page-header text-center lead">Nova Venda</h1>
      </div>
  </div> -->
  <div class="row">
      <div class="col-xs-10 col-md-12">
          <form action="" method="POST">
              {% csrf_token %}

              <legend>Venda</legend>
              <div class="row">
                  <div class="col-xs-8 col-md-5">
                      {{ forms|bootstrap }}
                      {{ formset.management_form|bootstrap }}
                  </div>
              </div>
              <legend class="lead">Produtos</legend>
              <div id="order" class="form-inline">
                  {% for item_order_form in formset %}
                  <div id="item-{{ forloop.counter0 }}" class="form-group">
                      {{ item_order_form|bootstrap }}
                  </div>
                  {% endfor %}
              </div>

              <a class="btn btn-info" id="add-item"><i class="fa fa-plus"></i>Add Item</a>

              <div class="form-inline buttons">
                  <a href="{% url 'core:sale_list' %}" class="btn btn-danger pull-right">
                      <i class="fa fa-times"></i>
                      Cancelar
                  </a>
                  <button class="btn btn-primary pull-right" value="Save">
                      <i class="fa fa-floppy-o"></i>
                      Salvar
                  </button>
              </div>

          </form>
      </div>
  </div>

    <script>
      $(document).ready(function () {
        $("#add-item").click(function (ev) {
          ev.preventDefault();
          var count = $('#order').children().length;
          var tmplMarkup = $("#item-order").html();
          var compiledTmpl = tmplMarkup.replace(/__prefix__/g, count);
          $("div#order").append(compiledTmpl);

          // update form count
          $('#id_product-TOTAL_FORMS').attr('value', count + 1);

          // some animate to scroll to view our new form
          $('html, body').animate({
            scrollTop: $("#add-item").position().top - 200
          }, 800);
          {# Initialize select2 on new select field #}
          $('#id_product-' + (count) + '-product').select2();
        });
        {# Initialize select2 on all select tags #}
        $('select').select2();
      });
    </script>

    <script type="text/html" id="item-order">
      <div id="item-__prefix__" class="form-group" style="margin-top: 10px">
        {{ formset.empty_form|bootstrap }}
      </div>
    </script>
{% endblock %}

vendas/core/templates/core/sale/sale_form_angular.html
{% extends "base.html" %}

{% block angulardependencies %}['vendas']{% endblock angulardependencies %}

{% block content %}
 <div class="container" ng-controller="VendasCtrl">
  <form class="form-horizontal" method="POST">
  {% csrf_token %}
  {{ form.non_field_errors }}

<!-- Agora eh AngularJS -->

	<span ng-show="m.loading">Carregando...</span>

  <select ng-model="m.produto" ng-options="p.product for p in m.produtos"></select>

  <input type="text" ng-model="m.produto.price">

  <button ng-click="m.adiciona_produto()" class="btn btn-primary">Adicionar</button>

<!-- Nao uso mais Django nesta pagina -->
{% for field in form %}
  <div class="form-group">
  <div class="control-label col-sm-2">
  {{ field.errors }}
  {{ field.label }}
  </div>
  <div class="col-sm-2">
  {{ field }}
  </div>
  </div>
  {% endfor %}
  <!-- <div class="form-group">
	  <div class="col-lg-offset-2 col-sm-10">
		  <button type="submit" class="btn btn-primary">Salvar</button>
	  </div>
  </div> -->

  <ul>
  	<li ng-repeat="produto in m.selected_products">{[{produto.product}]} - {[{produto.price}]}</li>
  </ul>

  <button ng-click="m.cria_pedido()" class="col-lg-offset-2 col-sm-10">Salvar</button>

  </form>
 </div>
{% endblock content %}

vendas/core/templates/core/sale/sale_form_teste.html
{% extends "base.html" %}

{% block content %}

<form class="form-horizontal" method="POST">
  {% csrf_token %}
  {{ form.non_field_errors }}

  {% for field in form %}
    <div class="form-group">
      <div class="control-label col-sm-2">
        {{ field.errors }}
        {{ field.label }}
      </div>
      <div class="col-sm-2">
        {{ field }}
      </div>
    </div>
  {% endfor %}

  <table class="form-inline">
    <thead>
      <tr>
        <th>Produto</th>
        <th>Quantidade</th>
        <th>Preço</th>
        <th>IPI</th>
      </tr>
    </thead>
    <tbody id="items">
      <tr>
        <td><input type="text" id="id_product" name="product[]" class="form-control"></td>
        <td><input type="text" id="id_quantity" name="quantity[]" class="form-control"></td>
        <td><input type="text" id="id_price_sale" name="price_sale[]" class="form-control"></td>
        <td><input type="text" id="id_ipi_sale" name="ipi_sale[]" class="form-control"></td>
      </tr>
    </tbody>
  </table>

  <div>
    <button id="add" onclick="" type="text" class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span></button>
  </div>


</form>

<!-- JavaScript -->
<script type="text/javascript">
  function send_form(){
    var p = $('input[name="product[]"]');
    var q = $('input[name="quantity[]"]');
    var ps = $('input[name="price_sale[]"]');
    var ipi = $('input[name="ipi_sale[]"]');

    var dados = {
      'product': [],
      'quantity': [],
      'price_sale': [],
      'ipi_sale': [],
    };

    for (var i = 0; i < p.length; i++) {
      dados['product'].push(p[i].value);
    }
    for (var i = 0; i < q.length; i++) {
      dados['quantity'].push(q[i].value);
    }
    for (var i = 0; i < ps.length; i++) {
      dados['price_sale'].push(ps[i].value);
    }
    for (var i = 0; i < ipi.length; i++) {
      dados['ipi_sale'].push(ipi[i].value);
    }

    var url = '/sale/';

    $.ajax({
      type: 'post',
      url: url,
      dataType: 'json',
      data: dados,
      error: function(){
        alert('Erro na requisição');
      },
      success: function(data){
        console.log(data);
      }
    });
    return false;
  }
</script>


  <script type="text/javascript">
  $(document).ready(function() {
    $('#add').click(function(e){
      e.preventDefault();
      $('#items').append('<tr>'+
                '<td><input type="text" id="id_product" name="product[]" class="form-control"></td>'+
                '<td><input type="text" id="id_quantity" name="quantity[]" class="form-control"></td>'+
                '<td><input type="text" id="id_price_sale" name="price_sale[]" class="form-control"></td>'+
                '<td><input type="text" id="id_ipi_sale" name="ipi_sale[]" class="form-control"></td>'+
              '</tr>');
    });

    $('#items').on('click','.rmfield', function(e){
      e.preventDefault();
      $(this).parents('tr').remove();
    });
  });
  </script>

{% endblock content %}

vendas/core/templates/core/sale/sale_list.html
{% extends 'base.html' %}

{% block content %}

    <form class="navbar-form navbar-right" action="." method="get">
        <!-- add -->
        <a href="{% url 'core:sale_add' %}">
            <button id="new_sale" type="button" class="btn btn-primary">
                <span class="glyphicon glyphicon-plus"></span> Adicionar
            </button>
        </a>
        <!-- search form -->
        <input id="search_box" name="search_box" type="text" placeholder="Localizar..." class="form-control">
        <button type="submit" class="btn btn-success form-control"><span class="glyphicon glyphicon-search"></span></button>
		
		<div class="text-right">
		<p>
			<spam name="filter_sale_zero"><a href="?filter_sale_zero=1">Vendas sem itens</a></spam>
			<spam name="filter_sale_one" style="padding-left:1.2em"><a href="?filter_sale_one=1">Vendas com um item</a></spam>
		</p>
		</div>
	</form>

	<h1>Lista de Vendas</h1>

{% if object_list %}
		<div>
			<table class="table">
				<thead>
					<tr>
						<th>Código</th>
						<th>Cliente</th>
						<th class="text-center">Data da venda</th>
						<th class="text-center">Itens</th>
						<th class="text-right">Total</th>
						<th>Vendedor</th>
					</tr>
				</thead>
				<tbody>
				{% for sale in object_list %}
					{% if sale.get_itens == 0 %}
						<tr class="danger">
					{% elif sale.get_itens == 1 %}
						<tr class="info">
					{% else %}
						<tr>
					{% endif %}
							<td><a href="{{ sale.get_detalhe }}">{{ sale.codigo }}</a></td>
							<td>{{ sale.customer.full_name }}</td>
							<td class="text-center">{{ sale.created|date:"d/m/Y" }}</td>
							<td class="text-center">{{ sale.get_itens }}</td>
							<td class="text-right">{{ sale.get_total }}</td>
							<td>{{ sale.seller.full_name }}</td>

						</tr>
				{% endfor %}
				</tbody>
			</table>
		</div>
{% else %}
  <p class="alert alert-warning">Sem itens na lista.</p>
{% endif %}

<hr>
<div>
<h3>{{ object_list|length }} venda{{ object_list|length|pluralize }}</h3>
<h4><b>Total:</b> {{ page_obj.paginator.count }} venda{{ page_obj.paginator.count|pluralize }}</h4>
</div>

{% if object_list %}
  <!-- pagination -->
  {% include "_pagination.html" %}
{% endif %}

{% endblock content %}